language: node_js

addons:
  apt:
    update: true

node_js:
  - "node"

install:
  - npm install jshint -g
  - npm install PrettyCSS -g
  - npm install js-beautify -g
  - npm install html-linter -g
  - bundle install

script:
  - ./lint.sh
  - bundle exec danger
